### PR TITLE
problem with vibe-d tests was resolved

### PR DESCRIPTION
**Pull request by MartinNowak**
- https://github.com/rejectedsoftware/vibe.d/issues/1844#issuecomment-315881639

### CODE REVIEW

**Comment by MartinNowak** [comment]
Apparently dedupremove clogged up lots of RAM in the pagecache, need to drop caches next time i'm deduplicating the disk.

**Comment by MartinNowak** [comment]
There is still the unable to join threads problem.
https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fci/detail/PR-54/1/pipeline/182#step-789-log-244

**Comment by wilzbach** [comment]
> There is still the unable to join threads problem.
https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fci/detail/PR-54/1/pipeline/182#step-789-log-244

I assume you are about to open an issue at Vibe.d about this?

**Comment by CyberShadow** [comment]
> Apparently dedupremove clogged up lots of RAM in the pagecache, need to drop caches next time i'm deduplicating the disk.

If you're deduplicating mostly-identical trees, then dedupremove is overkill. I wrote a much simpler program for this:

https://dump.thecybershadow.net/67742647f2ccae41a7f7a5daec83c400/btrfs-dedup-tree.d

**Pull request merged**
