### PR TITLE
Add CyberShadow/ae

### PR DESCRIPTION
**Pull request by CyberShadow**
This library is used for Digger, DAutoTest and DFeed.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Changes to the CI itself aren't tested?

**Comment by wilzbach** [comment]
> Changes to the CI itself aren't tested?

Nope not that I would know ...

**Comment by MartinNowak** [comment]
> Nope not that I would know ...

Changes against the CI repo itself would need to be integrated into https://github.com/dlang/phobos/blob/master/Jenkinsfile.
Alternatively we could use a bootstrap groovy file that loads the real pipeline script, see #44.

**Comment by MartinNowak** [comment]
Or just use a different Jenkinsfile in the ci repo :).

**Comment by MartinNowak** [comment]
Please check the output of https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fci/detail/master/2/pipeline/162#step-316-log-1 whether everything works as expected.
We're simply reading the script from the `.travis.yml` by default (with `dub test --compiler=$DC` as fallback just as on Travis-CI).

The workers actually do run on Btrfs btw ;).

**Comment by CyberShadow** [comment]
Yep, looks great! 

Perhaps I should exclude the network tests to avoid random failures due to changes in network conditions. Any advice on how do detect if it's running on the Jenkins CI from the D unittest?

> The workers actually does run on Btrfs btw ;).

It reads /proc/self/mounts and looks for the directory `pwd` is in, if that's somehow wrong/unavailable then it won't be detected.

**Pull request merged**
