### PR TITLE
Disable D-YAML

### PR DESCRIPTION
**Pull request by Geod24**
It is currently broken and holding back development.

CC @Herringway

### CODE REVIEW

**Comment by WalterBright** [comment]
Disabled because of the following errors:
```

  | Preparing working directory | 2s
-- | -- | --
  | Running commands | 0s
  | Load distribution archive | 4s
  | Setting build variables | 1s
  | Checking dlang-community/D-YAML for a core repository and branch merging with https://github.com/dlang/dmd.git | 0s
  | Cloning https://github.com/dlang-community/D-YAML (tag: v0.8.0) | 2s
  | Running the testsuite | 17s
  | ~> case "$REPO_FULL_NAME" in
  | ~> dub build --compiler=dmd
  | Fetching tinyendian 0.2.0 (getting selected version)...
  | Performing "debug" build using dmd for x86_64.
  | dyaml 0.8.0: building configuration "library"...
  | ~> dub test --compiler=dmd
  | Generating test runner configuration 'dyaml-test-library' for 'library' (library).
  | Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
  | Performing "unittest" build using dmd for x86_64.
  | tinyendian 0.2.0: building configuration "library"...
  | dyaml 0.8.0: building configuration "dyaml-test-library"...
  | source/dyaml/node.d(502,36): Error: template instance `AliasSeq!this` template `AliasSeq` is not defined
  | source/dyaml/node.d(638,24): Error: template instance `dyaml.node.Node.as!(MyStruct, cast(Flag)true)` error instantiating
  | source/dyaml/node.d(502,36): Error: template instance `AliasSeq!this` template `AliasSeq` is not defined
  | source/dyaml/node.d(677,24): Error: template instance `dyaml.node.Node.as!(MyStruct, cast(Flag)true)` error instantiating
  | source/dyaml/node.d(502,36): Error: template instance `AliasSeq!this` template `AliasSeq` is not defined
  | source/dyaml/node.d(719,24): Error: template instance `dyaml.node.Node.as!(MyStruct, cast(Flag)true)` error instantiating
  | source/dyaml/node.d(502,36): Error: template instance `AliasSeq!this` template `AliasSeq` is not defined
  | source/dyaml/node.d(775,24): Error: template instance `dyaml.node.Node.as!(MyClass, cast(Flag)true)` error instantiating
  | dmd failed with exit code 1.
  | 🚨 Error: The command exited with status 2
```

**Comment by wilzbach** [comment]
You do realize that this very much looks like a regression?

**Comment by MoonlightSentinel** [comment]
> You do realize that this very much looks like a regression?

Agreed, 2.092.0 passes but current master fails with the aforementioned error,

```
> dub test -f
Generating test runner configuration 'dyaml-test-library' for 'library' (library).
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Performing "unittest" build using C:\D\dmd2\windows\bin64\dmd.exe for x86_64.
tinyendian 0.2.0: building configuration "library"...
dyaml 0.8.0: building configuration "dyaml-test-library"...
Linking...
Running .\dyaml-test-library.exe
19 unittests passed

> dub test --compiler="dmd\generated\windows\release\64\dmd.exe" -f                                   Generating test runner configuration 'dyaml-test-library' for 'library' (library).
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Performing "unittest" build using dmd\generated\windows\release\64\dmd.exe for x86_64.
tinyendian 0.2.0: building configuration "library"...
dyaml 0.8.0: building configuration "dyaml-test-library"...
source\dyaml\node.d(502,36): Error: template instance AliasSeq!this template AliasSeq is not defined
source\dyaml\node.d(638,24): Error: template instance dyaml.node.Node.as!(MyStruct, cast(Flag)true) error instantiating
source\dyaml\node.d(502,36): Error: template instance AliasSeq!this template AliasSeq is not defined
source\dyaml\node.d(677,24): Error: template instance dyaml.node.Node.as!(MyStruct, cast(Flag)true) error instantiating
source\dyaml\node.d(502,36): Error: template instance AliasSeq!this template AliasSeq is not defined
source\dyaml\node.d(719,24): Error: template instance dyaml.node.Node.as!(MyStruct, cast(Flag)true) error instantiating
source\dyaml\node.d(502,36): Error: template instance AliasSeq!this template AliasSeq is not defined
source\dyaml\node.d(775,24): Error: template instance dyaml.node.Node.as!(MyClass, cast(Flag)true) error instantiating
dmd\generated\windows\release\64\dmd.exe failed with exit code 1.
```

**Comment by MoonlightSentinel** [comment]
Forget that, it rather seems like an accidental bugfix ... the failing test doesn't import `AliasSeq` AFAICT.

**Comment by wilzbach** [comment]
DYAML 0.8.0 was released on 2019-05-26, so it's technically still a regression. We broke code that used to work.
Anyhow, sometimes we fix the project if a deprecation would be too hard to implement or the fix was crucial, but I am complaining because the CI was working properly and was just ignored as "unrelated failure" and I'm pretty sure if we dig deeper into this we'll find the root cause PR that was merged with failing checks :/

**Comment by Geod24** [comment]
Didn't have the time for that earlier, but I did now, so I dig deeper... [And you'll never guess what I found](https://github.com/dlang/phobos/pull/7473#issuecomment-628176305).

**Comment by Herringway** [comment]
Sure wasn't expecting to wake up to this... But anyway, 0.8.1 has been tagged.

**Comment by WalterBright** [comment]
Ironically, @Geod24 's fix fails with: "CyberShadow/DAutoTest — Build failed". Sigh.

**Comment by WalterBright** [comment]
(Thank you, @Geod24 , for finding the cause. You da man!)

**Pull request merged**
