### PR TITLE
Revert "Disable Mecca pending PR merge"

### PR DESCRIPTION
**Pull request by wilzbach**
Reverts dlang/ci#393

CC @Geod24

### CODE REVIEW

**Comment by Geod24** [comment]
Blocked on https://github.com/weka-io/mecca/pull/23

**Comment by Geod24** [comment]
Why is this green ? 🤔

**Comment by wilzbach** [comment]
Because master has the linking change, but not stable.

**Comment by Geod24** [comment]
Mecca PR merged

**Pull request merged**
