### PR TITLE
Remove network tests for ae due to frequent timeouts

### PR DESCRIPTION
**Pull request by wilzbach**
```
Testing AENetwork
 - getFile
object.Exception@sys/net/ae.d(33): Time-out
----------------
sys/net/ae.d:33 pure @safe void ae.sys.net.ae.AENetwork.getData(immutable(char)[]).__lambda3(immutable(char)[]) [0x8f643b]
net/http/client.d:379 void ae.net.http.client.httpRequest(ae.net.http.common.HttpRequest, void delegate(ae.sys.data.Data), void delegate(immutable(char)[]), int).responseHandler(ae.net.http.common.HttpResponse, immutable(char)[]) [0x887377]
net/http/client.d:201 void ae.net.http.client.HttpClient.processResponse(immutable(char)[]) [0x886b16]
net/http/client.d:210 void ae.net.http.client.HttpClient.onDisconnect(immutable(char)[], ae.net.asockets.DisconnectType) [0x886b6a]
net/asockets.d:1398 void ae.net.asockets.ConnectionAdapter.onDisconnect(immutable(char)[], ae.net.asockets.DisconnectType) [0x7b66ba]
net/asockets.d:1589 void ae.net.asockets.TimeoutAdapter.onDisconnect(immutable(char)[], ae.net.asockets.DisconnectType) [0x7b70b1]
net/asockets.d:944 void ae.net.asockets.StreamConnection.disconnect(immutable(char)[], ae.net.asockets.DisconnectType) [0x7b4e58]
net/asockets.d:1380 void ae.net.asockets.ConnectionAdapter.disconnect(immutable(char)[], ae.net.asockets.DisconnectType) [0x7b6593]
net/asockets.d:1613 void ae.net.asockets.TimeoutAdapter.onTask_Idle(ae.sys.timing.Timer, ae.sys.timing.TimerTask) [0x7b71b0]
sys/timing.d:212 bool ae.sys.timing.Timer.prod() [0x90102b]
net/asockets.d:417 void ae.net.asockets.SocketManager.loop() [0x7b3a64]
sys/net/ae.d:36 ae.sys.data.Data ae.sys.net.ae.AENetwork.getData(immutable(char)[]) [0x8f62b3]
sys/net/ae.d:49 void[] ae.sys.net.ae.AENetwork.getFile(immutable(char)[]) [0x8f652b]
sys/net/test.d:39 void ae.sys.net.test.test!("ae", "AENetwork").test() [0x8fb7fa]
sys/net/test.d:75 void ae.sys.net.test.__unittest_ae_sys_net_test_73_0() [0x8fb6f0]
??:? void ae.sys.net.test.__modtest() [0x8fc294]
??:? int core.runtime.runModuleUnitTests().__foreachbody2(object.ModuleInfo*) [0xa4046f]
??:? int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)).__lambda2(immutable(object.ModuleInfo*)) [0x9dffa6]
??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))).__foreachbody2(ref rt.sections_elf_shared.DSO) [0x9ed025]
??:? int rt.sections_elf_shared.DSO.opApply(scope int delegate(ref rt.sections_elf_shared.DSO)) [0x9ed488]
??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))) [0x9ecfb1]
??:? int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)) [0x9dff7d]
??:? runModuleUnitTests [0xa40245]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x9e768c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x9e7613]
??:? _d_run_main [0x9e757e]
??:? main [0x7b3119]
??:? __libc_start_main [0xf1c7f82f]
1/74 unittests FAILED
Program exited with code 1
script returned exit code 2
```

https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/detail/PR-7815/3/pipeline/

FYI @CyberShadow - imho this is the best course of action for now.
If you ever add a start a stub fileserver on the testsuite, please feel free to remove this.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Thanks. See here: https://github.com/CyberShadow/ae/issues/30

Martin never got back to me to a way to detect that we're running under the project tester, so in the end I re-enabled them. Now there is some server maintenance causing timeouts...

**Comment by CyberShadow** [comment]
> If you ever add a start a stub fileserver on the testsuite, please feel free to remove this.

You're right, that's probably the best solution. I've been a little adverse to it, because relying on your own code to validate the results of the code you're testing is a little fallacious (e.g. a bug in the headers module might cause invalid headers to be generated but also parsed successfully). But there's a variety of APIs being tested, so that shouldn't be an issue.

**Comment by wilzbach** [comment]
>  I've been a little adverse to it, because relying on your own code to validate the results of the code you're testing is a little fallacious (e.g. a bug in the headers module might cause invalid headers to be generated but also parsed successfully).


Well, I was more thinking about using sth. simple and built-in like  `python -m http.server`

If you prefer the D way, have a look at what Martin and I have been doing to test `dub`: https://github.com/dlang/dub/pull/1339/files#diff-377deb8b00fdba297690de34b920e9bf

**Comment by CyberShadow** [comment]
ae does have a HTTP server, so that's not the issue. But re-reading https://github.com/CyberShadow/ae/issues/30 I remembered there was another problem with this idea, testing SSL.

**Comment by MartinNowak** [comment]
I just suggested DETERMINISTIC=1 to @atilaneves, should work universally no?
Let's make it DETERMINISTIC_TESTS=1.

**Comment by MartinNowak** [comment]
> Martin never got back to me to a way to detect that we're running under the project tester, so in the end I re-enabled them. Now there is some server maintenance causing timeouts...

If it's important you can reach me under dlang.slack.com or via Signal, I don't reliably read anything but IM, and even that only when I have time.

**Comment by CyberShadow** [comment]
Thanks. It wasn't important (to me), but it seemed odd that you created the GitHub issues and then disappeared and never read my replies. Also, IMHO, if a message is explicitly mentioning you by name, that should end up in your inbox.

**Comment by MartinNowak** [comment]
> Also, IMHO, if a message is explicitly mentioning you by name, that should end up in your inbox.

It prolly does, I don't care though if I don't have time or am focues on sth. else, and people ask me stuff all the time. BTW, https://octobox.io/ is quite nice, but obviously cannot reduce the volume of questions or distractions.

**Comment by CyberShadow** [comment]
> It prolly does, I don't care though if I don't have time or am focues on sth. else, and people ask me stuff all the time.

Err, well, that just raises more questions. Email/GitHub is not real-time, so just leave those to queue up and answer them when you do have the time?

> BTW, https://octobox.io/ is quite nice

That looks completely superfluous to a well-configured email setup.

**Pull request merged**
