### PR TITLE
use Travis-CI command to test ocean

### PR DESCRIPTION
**Pull request by MartinNowak**
- also add beaver to PATH

### CODE REVIEW

**Comment by mihails-strasuns** [comment]
beaver is a shell utility on top of docker, haven't you mentioned that you don't want to use it for now?

**Comment by MartinNowak** [comment]
I see, read this

> To use Docker in you builds, Beaver expects a Dockerfile

as optional docker support.

**Comment by mihails-strasuns** [comment]
No, sorry for misleading wording. Maybe @leandro-lucarella-sociomantic originally intended it may work both ways thus put it into readme like that, but right now it is tightly tied to docker.

**Comment by leandro-lucarella-sociomantic** [comment]
Yeah, even when beaver is not really tied to docker, I think at the moment all tools use docker. If we are not calling beaver from the build scripts, then there is no point in adding beaver to the path.

Also, I don't know what `test_travis_yaml()` is for, but our travis build uses docker, so if docker is not available here, you probably want to ignore the travis.yml file too.

**Comment by MartinNowak** [comment]
> test_travis_yaml()

Just executes the script of a `.travis.yml`, but nothing else.

**Pull request closed without merging**
