### PR TITLE
Try to nuke ~/.dub once

### PR DESCRIPTION
**Pull request by wilzbach**
Required for https://github.com/dlang/phobos/pull/5921

### CODE REVIEW

**Comment by wilzbach** [comment]
On a second thought. We already use a local mirror, so let's see whether this adds a noticeable time to Jenkins, it's quite likely that we run into issues with this again & either doing a PR to nuke `~/.dub`  (or waiting for the worker to die and be "resurrected") doesn't sound like the best idea.

**Comment by MartinNowak** [comment]
The was not related to fetched ddox packages last time I debugged sth. similar. It was rather a hardcoded fetch in dub's test-suite or so.

And no deleting `~/.dub` is not OK, packages have to be re-downloaded from **github**.
That's also the wrong place to delete `.dub` (it's on the node that builds dlang), we use one `.dub` folder per testee.

**Comment by wilzbach** [comment]
Sorry - it was just an experiment.

**Comment by MartinNowak** [comment]
No worries, just want to let you know why we cache things.

**Comment by MartinNowak** [comment]
I've manually deleted ddox-* on all slaves.

**Pull request closed without merging**
