### PR TITLE
Login via Github

### PR DESCRIPTION
**Pull request by MartinNowak**
E.g. in order to trigger rebuilds.
https://wiki.jenkins-ci.org/display/JENKINS/GitHub+OAuth+Plugin

### CODE REVIEW

**Comment by wilzbach** [comment]
Wow I didn't know this existed :)

**Comment by MartinNowak** [comment]
> Wow I didn't know this existed :)

Let me know if sth. doesn't work for you. I'll soon tell everyone else.

**Comment by wilzbach** [comment]
Works nicely so far. Thanks a lot :)

**Comment by MartinNowak** [comment]
When you click on the linked jenkins status here in GH, the login button is a bit hidden (trying to change that with https://github.com/jenkinsci/blueocean-plugin/pull/1260).
For example going to https://ci.dlang.io/job/dlang-org/job/druntime/job/PR-1886/1/display/redirect,
click on the `x`
x
to close the overlayed result page, then you should see a login button in the normal header.
login

**Pull request merged**
