### PR TITLE
Dockerfile: Add LLVM 15, the min version required for LDC v1.39

### PR DESCRIPTION
**Pull request by kinke**
The existing LLVM 14 (Ubuntu 22 default) is too old.

### CODE REVIEW

**Comment by kinke** [comment]
Btw, https://github.com/dlang/ci/blob/7953cbac1c3a5e2f13fdf4068be3d1a92b22838c/buildkite/Dockerfile#L3-L5 made me ignore the Dockerfile at first.

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
My runners have been rebuilt, I've pinged @ibuclaw so he rebuild his.

**Comment by RazvanN7** [comment]
ldc is still failing on buildkite for all new dmd PRs. Are there any additional steps that need to be done to make it green again?

**Comment by Geod24** [comment]
@ibuclaw : Looks like your runners haven't rebuild ?

**Comment by ibuclaw** [comment]
> @ibuclaw : Looks like your runners haven't rebuild ?

I thought I added a crontjob to do this daily - I checked again and it looks like it was rather every Monday.  I've tweaked this to be a bit more aggressive in checking.

**Comment by ibuclaw** [comment]
One of the runners died too, which didn't help the process.
```
Aug 22 07:51:18 zaphod docker[3611747]: 2024-08-22 07:51:18 WARN   zaphod-2 Failed to ping: GET https://agent.buildkite.com/v3/ping: 502 Bad Gateway (Last successful was 4.992204777s ago)
```

I have a few update scripts stuck waiting for this runner to report `Waiting for work`

**Comment by ibuclaw** [comment]
Cleared down the backlog now.  @Geod24 you're behind now. :-)
image

**Pull request merged**
