### PR TITLE
Use master as fallback for non-existent branches

### PR DESCRIPTION
**Pull request by wilzbach**
When a PR is made directly from an upstream branch or to a different
branch than `master` or `stable`, the respective branch at the other two
repositories might not exist. So let's better check beforehand and
softly fallback to `master` otherwise. The same procedure is e.g. used
for CircleCi.

Note: I'm doing this more or less blind :/

### CODE REVIEW

**Comment by wilzbach** [comment]
Example for such a failure: https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/detail/revert-7416-fix18053/1/pipeline (from https://github.com/dlang/dmd/pull/7505)

**Comment by MartinNowak** [comment]
The failing test is a bad example, it's running a test for the revert branch in dlang/dmd, not for the PR.
The PR test is here https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/detail/PR-7505/1/pipeline and doesn't fail.

Limit branch tests wouldn't work with feature branches. In fact https://ci.dlang.io/job/dlang-org/job/dmd/configure already uses `Exclude branches that are also filed as PRs`, so the branch shouldn't have been tested separately. Also I think using GH's revert button used to work correctly, maybe the PR hook arrived after the branch hook? Did GH link to the branch test or to the PR test?
```
[Sun Dec 24 09:35:54 UTC 2017] Finished processing Push event to branch revert-7416-fix18053 in repository dlang/dmd CREATED event from 10.23.2.1 ⇒ https://ci.dlang.io:8080/github-webhook/ with timestamp Sun Dec 24 09:35:48 UTC 2017. Matched 1.
[Sun Dec 24 09:36:54 UTC 2017] Received Pull request #7505 opened in repository dlang/dmd CREATED event from 10.23.2.1 ⇒ https://ci.dlang.io:8080/github-webhook/ with timestamp Sun Dec 24 09:36:49 UTC 2017
Found match against dlang-org/dmd (new branch PR-7505)
[Sun Dec 24 09:36:56 UTC 2017] Finished processing Pull request #7505 opened in repository dlang/dmd CREATED event from 10.23.2.1 ⇒ https://ci.dlang.io:8080/github-webhook/ with timestamp Sun Dec 24 09:36:49 UTC 2017. Matched 1.
[Mon Dec 25 21:22:14 UTC 2017] Received Pull request #7505 closed in repository dlang/dmd REMOVED event from 10.23.2.1 ⇒ https://ci.dlang.io:8080/github-webhook/ with timestamp Mon Dec 25 21:22:09 UTC 2017
[Mon Dec 25 21:22:16 UTC 2017] Finished processing Pull request #7505 closed in repository dlang/dmd REMOVED event from 10.23.2.1 ⇒ https://ci.dlang.io:8080/github-webhook/ with timestamp Mon Dec 25 21:22:09 UTC 2017. Matched 1.
[Mon Dec 25 21:22:20 UTC 2017] Received Push event to branch revert-7416-fix18053 in repository dlang/dmd REMOVED event from 10.23.2.1 ⇒ https://ci.dlang.io:8080/github-webhook/ with timestamp Mon Dec 25 21:22:15 UTC 2017
[Mon Dec 25 21:22:21 UTC 2017] Finished processing Push event to branch revert-7416-fix18053 in repository dlang/dmd REMOVED event from 10.23.2.1 ⇒ https://ci.dlang.io:8080/github-webhook/ with timestamp Mon Dec 25 21:22:15 UTC 2017. Matched 1.
```

While we do have fallbacks for non-existing branch targets, this whole mechanism is to support feature branches. While working on the ctfe feature, we figured, it's better to create feature branches for all dlang repos, to pin them. But anyhow adding the fallbacks simplifies a few things, so let's add them to jenkins.

**Comment by wilzbach** [comment]
> Did GH link to the branch test or to the PR test?

Yes, that's why I submitted the PR in the first place. I have seen it a couple of times before in the past, e.g. if someone created a branch under `dlang` directly via GitHub.

> While we do have fallbacks for non-existing branch targets, this whole mechanism is to support feature branches. While working on the ctfe feature, we figured, it's better to create feature branches for all dlang repos, to pin them. 

Feature branches were an awesome idea!

> anyhow adding the fallbacks simplifies a few things, so let's add them to jenkins.

I am currently on my phone and see this is still failing. I will have a look at it soon.

**Comment by MartinNowak** [comment]
> I am currently on my phone and see this is still failing. I will have a look at it soon.

Already on it ;).

**Comment by wilzbach** [comment]
Thanks!

**Pull request merged**
