### PR TITLE
Add DStep to the tested projects

### PR DESCRIPTION
**Pull request by jacob-carlborg**

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Why is it checking out the latest tag? I want it to test master.

**Comment by jacob-carlborg** [comment]
I looked down the clone to the current master. I'll remove this later when a new tag is added for DStep.

**Comment by wilzbach** [comment]
It looks like the Jenkins Git checkout plugin only supports tags and branches :O

**Comment by jacob-carlborg** [comment]
Added a tag.

**Comment by jacob-carlborg** [comment]
It's Dub that is failing.

**Comment by wilzbach** [comment]
Yeah that's unrelated and due to https://github.com/dlang/ci/issues/135

However, I can't overwrite the CI check here. I will try to restart it.

**Comment by MartinNowak** [comment]
Downloading a 200+MiB clang+llvm for every test is **not OK**, please don't unnecessarily waste resources, simply because they are not your resources.
https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fci/detail/PR-146/2/pipeline/207#step-472-log-8
I've installed [libclang-4.0-dev](https://packages.ubuntu.com/xenial-updates/libclang-4.0-dev) on all testers. I'm reverting *this* until dstep manages to detect that package.
https://github.com/dlang/ci/pull/148
Let us know if you need sth. else installed.

You should also fix your Travis-CI tests to either use packages or at least cache the downloads, it's currently downloading 13x200+MiB from the llvm site.
https://travis-ci.org/jacob-carlborg/dstep/builds/334364953

**Comment by MartinNowak** [comment]
FYI @jacob-carlborg

**Comment by jacob-carlborg** [comment]
> You should also fix your Travis-CI tests to either use packages or at least cache the downloads, it's currently downloading 13x200+MiB from the llvm site.
https://travis-ci.org/jacob-carlborg/dstep/builds/334364953

Should I cache that to reduce the traffic to the LLVM site? Because the Travis documentation says:

"Large files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source:" [1]

[1] https://docs.travis-ci.com/user/caching/#Things-not-to-cache

**Comment by jacob-carlborg** [comment]
> You should also fix your Travis-CI tests to either use packages.

I cannot use packages because they are too old. I want to control myself which versions of LLVM I support.

**Pull request merged**
