### PR TITLE
Revert "Disable {libevent,vibe-core}-tests"

### PR DESCRIPTION
**Pull request by Geod24**
Reverts dlang/ci#412

v0.8.50 has been released.

### CODE REVIEW

**Comment by Geod24** [comment]
@s-ludwig: Still failing with v0.8.50 :(

**Comment by s-ludwig** [comment]
The changes have uncovered another bug in vibe-core: https://github.com/vibe-d/vibe-core/pull/198/commits/ad6cc71074cab8b5ebc9bd2298829554035803f9

I'm still waiting for the macOS CI workers. BTW, since this tests vibe.d master, the libevent test can be removed, as only vibe-core exists as a backend now.

**Comment by s-ludwig** [comment]
Okay, finally green again.

**Comment by Geod24** [comment]
Nice, thanks!

**Comment by Geod24** [comment]
>  BTW, since this tests vibe.d master, the libevent test can be removed, as only vibe-core exists as a backend now.

Will address in a separate PR.

**Pull request merged**
