### PR TITLE
test vibe 0.7.x to workaround Issue 1844

### PR DESCRIPTION
**Pull request by MartinNowak**
- https://github.com/rejectedsoftware/vibe.d/issues/1844

### CODE REVIEW

**Comment by ZombineDev** [comment]
Have you had the chance to test [v0.8.1-alpha.1](https://github.com/rejectedsoftware/vibe.d/releases/tag/v0.8.1-alpha.1)?
It should fix those failures, see:
https://dlang.slack.com/archives/C0JP1U9L5/p1499933603837559?thread_ts=1499871824.837134&cid=C0JP1U9L5

**Comment by wilzbach** [comment]
> Have you had the chance to test v0.8.1-alpha.1?

FYI: New DUB updates are automatically applied as the latest tag is fetched.

**Comment by wilzbach** [comment]
~~FYI: New DUB updates are automatically applied as the latest tag is fetched.~~

Please ignore. I didn't look properly.

**Comment by MartinNowak** [comment]
See the bug report, I'm still seeing a long delay (alsoo the 2 listenTCP calls now collide).

**Pull request merged**
