### PR TITLE
Add D-YAML to the Jenkins Autotester

### PR DESCRIPTION
**Pull request by wilzbach**
After D-YAML broke now twice this month due to regressions:
- https://github.com/dlang-community/D-YAML/issues/66
- https://github.com/dlang-community/D-YAML/issues/63

Imho it's time to test it on project tester:

### CODE REVIEW

**Comment by wilzbach** [comment]
Other interesting, popular D projects:
- https://github.com/gnunn1/tilix
- https://github.com/eBay/tsv-utils-dlang
- https://github.com/PhilippeSigaud/Pegged
- https://github.com/CyberShadow/ae
- https://github.com/atilaneves/reggae
- https://github.com/atilaneves/cerealed
- https://github.com/msoucy/dproto

**Comment by MartinNowak** [comment]
Hope the `.travis.yml` config will work, the `TRAVIS_OS` env variable will be undefined.

**Comment by CyberShadow** [comment]
> https://github.com/CyberShadow/ae

Yes please.

What are the criteria of accepted projects? Anything I need to do from my side?

**Comment by wilzbach** [comment]
> What are the criteria of accepted projects? 

It's not well-defined. I assume some mixture between:
- popular library / project
- alive (maintainers can be reached)
- easy to integrate (no complex dependency list)

I think `ae` fullfils all ;-)

> Anything I need to do from my side?

Submitting a PR like this one?

**Comment by CyberShadow** [comment]
How does the CI select versions? Does it build the latest tag?

**Comment by wilzbach** [comment]
> Hope the .travis.yml config will work, the TRAVIS_OS_NAME env variable will be undefined.

Hmm in theory only `dub test` should do everything, we aren't interested in testing mesos anyways.
Yeah it would be cool if we have the project tester configured for this repo as well, so that we can test changes easily.

**Comment by wilzbach** [comment]
> How does the CI select versions? Does it build the latest tag?

It selects the latest tag (see the script for details and hacks when this isn't wanted).

**Comment by CyberShadow** [comment]
Thanks. https://github.com/dlang/ci/pull/43

**Pull request merged**
