### PR TITLE
Disable Buildkite for dmd-cxx

### PR DESCRIPTION
**Pull request by wilzbach**
FYI @ibuclaw

### CODE REVIEW

**Comment by ibuclaw** [comment]
Missing an early return?

**Comment by wilzbach** [comment]
> Missing an early return?

Argh. Yes. Thanks! It was definitely too late when I opened up this PR.

**Comment by ibuclaw** [comment]
```
buildkite.sh: line 6: return: can only `return' from a function or sourced script
```
;-)

**Comment by wilzbach** [comment]
Argh -> https://github.com/dlang/ci/pull/374

**Pull request merged**
