### PR TITLE
Add dagon to the Project Tester

### PR DESCRIPTION
**Pull request by wilzbach**
CC @gecko0307 are you okay with having a bit more testing of your projects?
For this to work, I think you need to update dlib, s.t. it doesn't use the removed `std.c` modules.
Then in the future, such hard breakage can't happen again.

### CODE REVIEW

**Comment by gecko0307** [comment]
@wilzbach if you mean `std.c` error with latest DMD, then it's fixed (https://github.com/gecko0307/dlib/commit/ba8e0b9dbdece5e975cd166da1c1decc5f1f4196). It's not released yet, so Dagon doesn't compile with 2.081.0 right now.

**Comment by wilzbach** [comment]
Yep, I was referring to this. Could you give me a quick ping once its released?

**Comment by gecko0307** [comment]
Sure.

**Comment by gecko0307** [comment]
Now Dagon should compile with DMD 2.081.0 and LDC 1.10.0.

**Comment by gecko0307** [comment]
Are only releases tested there? I'm asking because master branch now works, but there's still a lot of work to be done until the next version of Dagon.

**Comment by wilzbach** [comment]
> Are only releases tested there?

Yes, the latest git tag is tested here. However, it currently fails as the `dub.selections.json` file has priority over the `dub.json` file and in `dub.selections.json` you still reference dlib 0.13
Thus I get the same error when I run `dub test` locally.

>  but there's still a lot of work to be done until the next version of Dagon.

Well, the idea of the project tester is that once added a new DMD release doesn't break your testsuite anymore (or each individual PR to be exact).
All that matters to is that you don't `git tag` a new release that fails your testsuite, that's the only big condition for projects being here ;-)
That being said, if you want to wait to the next version of Dagon, that would be totally fine for me.

**Comment by ZombineDev** [comment]
Thanks for the ping, I started a new build.

**Comment by wilzbach** [comment]
```
Error processing arguments: Missing value for argument --arch=.
```

It looks like either we should set `ARCH` or need a custom build command here. Probably just setting `ARCH` might be easier though.

**Comment by wilzbach** [comment]
> Probably just setting ARCH might be easier though.

Did this in https://github.com/dlang/ci/pull/218/commits/a1968a4f181bf60bb59789be7c573eb660117232

**Pull request merged**
