### PR TITLE
Add sqlite3 dependency for dlang-bot

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Oh, I have no power here.

**Comment by RazvanN7** [comment]
It's better if a maintainer will take a closer look. I am not convinced I didn't miss anything. cc @Geod24

**Review by wilzbach — APPROVED** [review]

**Comment by wilzbach** [comment]
LGTM

**Comment by RazvanN7** [comment]
Thanks!

**Comment by RazvanN7** [comment]
Is the dmd tester going to pick up this latest version or anything else needs to be done?

**Comment by wilzbach** [comment]
I think it needs to be redeployed manually, so you might have to message Martin and possibly @Geod24 if he's still running some testers as well.

**Comment by Geod24** [comment]
Not running any tester ATM.

**Comment by andralex** [comment]
Thanks. What do I need to do to get https://github.com/dlang/dmd/pull/12560 going?

**Comment by ibuclaw** [comment]
All dmd PRs have been broken > 24 hours. Revert?

**Pull request merged**
