### PR TITLE
Re-enable unit-threaded

### PR DESCRIPTION
**Pull request by atilaneves**

### CODE REVIEW

**Review by MoonlightSentinel — APPROVED** [review]

**Comment by Geod24** [comment]
```
~> bash
--
  | TERM environment variable not set.
```

**Comment by atilaneves** [comment]
I think the failure was caused by the CI scripts clearing the console but TERM isn't set when run from buildkite. I just pushed a new version of unit-threaded so here's hoping this passes now, especially since it being disabled allowed a regression to sneak through to dmd.

**Comment by Geod24** [comment]
@atilaneves : You need to tag a new release, Buildkite doesn't use master.

**Comment by atilaneves** [comment]
Debugging why this fails is "fun". Googled and tried but can't reproduce a local environment with TERM not set. Except maybe a cron job?

**Comment by MoonlightSentinel** [comment]
Commented on the commit, your workaround does not work with `set -u`.

**Comment by atilaneves** [comment]
> Commented on the commit, your workaround does not work with `set -u` AFAICT

Any ideas?

**Comment by MoonlightSentinel** [comment]
https://github.com/atilaneves/unit-threaded/commit/4213bfb9b5b06f541281e692688e81fb9090ec65#r41781457

**Comment by Geod24** [comment]
I see you gave up :D

**Pull request merged**
