### PR TITLE
Remove Basile-z/iz from the list of packages

### PR DESCRIPTION
**Pull request by Geod24**
The user apparently deleted their Github account.

### CODE REVIEW

**Comment by Geod24** [comment]
Also disabling `aliak/optional` as it seems packages can't be fetched from Gitlab.
CC @aliak00

**Comment by aliak00** [comment]
@Geod24 Gitlab? You mean github? -> https://github.com/aliak00/optional
Why can't it be fetched?

**Comment by wilzbach** [comment]
One of your dependencies is on gitlab and the dub registry seems to crash on gitlab dependencies.

**Comment by aliak00** [comment]
Oh. That'd be silly then. Is it a dub problem? Because locally at least (i just deleted the package from ~/.dub) running dub test fetched from gitlab without problems?

**Comment by wilzbach** [comment]
> Oh. That'd be silly then. Is it a dub problem?

Yeah it's really silly and a dub registry problem, but we had to revert it a week ago already (https://github.com/dlang/ci/pull/399).
Here's an example: https://buildkite.com/dlang/dmd/builds/8798#c7f66aa9-d746-4f7e-8d3f-d2d981088e4f

The problem is that if you go to https://code.dlang.org/packages/silly/0.8.2.zip, you directly get a 502 from the dub registry :/
I opened an issue here, but I guess a workaround for now would be to register a GitHub fork (`silly-gh`) :/

**Comment by aliak00** [comment]
Boh. Ok. Thanks for the info. I'll ping here if I get around to forking
silly on gh as a workaround or something.

**Comment by wilzbach** [comment]
> I'll ping here if I get around to forking silly on gh as a workaround

I think @FeepingCreature has expressed interest in implementing `git` support for `dub`, then you could just use sth. like `git://gitlab.com/../silly.git` and it would never even query the dub registry.

**Pull request merged**
