### PR TITLE
Unshallow git history for dlang-tour builds

### PR DESCRIPTION
**Pull request by wilzbach**
Should hopefully fix Buildkite.

### CODE REVIEW

**Comment by joakim-noah** [comment]
Maybe better to update the git packages?

**Comment by wilzbach** [comment]
> Maybe better to update the git packages?

Ah it would then just fail again once a new commit gets added to dlang-tour/english.
However, it looks like even this doesn't solve the issue :/

**Comment by joakim-noah** [comment]
>Ah it would then just fail again 

How? It works for me now with git 2.19.2, ie I don't need these changes.

**Comment by wilzbach** [comment]
Well yeah I have no idea anymore what's going on at the agents and I ran out of ideas for now.

**Comment by wilzbach** [comment]
> What is the git version used by the agent ? 

I don't know it either, but upgrading is a bit hard as they use a default Ubuntu image.

> Other option than updating the git version would be to clone without depth set to 1

Isn't `unshallow` going to fix this retro-actively?

**Comment by ZombineDev** [comment]
Another reason to drop the shitty setup (w.r.t. build env, not infra) and use Docker ;)

**Comment by joakim-noah** [comment]
#365 reports `git version 2.11.0`, [which was released more than two years ago](https://blog.github.com/2016-11-29-git-2-11-has-been-released/).

**Comment by wilzbach** [comment]
No Martin just has some auto-adjusting of agents in place. Though it looks like its not working properly.

**Comment by joakim-noah** [comment]
Fixed in #366, I don't know what's up with the other killed builds.

**Comment by joakim-noah** [comment]
Can be closed, already fixed.

**Comment by joakim-noah** [comment]
btw, ldc is now timing out on Buildkite, didn't used to before. It uses two cores to build itself, `ninja -j2`: can that be increased to make sure it doesn't hit the 40 min. timeout or will it not help on the hardware being used?

**Comment by wilzbach** [comment]
I honestly don't know whether this would help, but it's worth a try. Otherwise we could increase the timeout to 60 minutes.

**Pull request closed without merging**
