### PR TITLE
Buildkite: Use git clean flags in build_project as well

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Comment by Geod24** [comment]
For reference:
```
# Systemd unit file to run buildkite instances
#
[Unit]
Description=Buildkite CI runner
After=network.target local-fs.target

[Service]
ExecStart=/usr/bin/docker run --rm runner -- start --token $TOKEN_GOES_HERE --tags="memory=high" --name $USERNAME_GOES_HERE-%I
Restart=always

[Install]
WantedBy=multi-user.target
```

```sh
# systemctl enable buildkite@1
Created symlink /etc/systemd/system/multi-user.target.wants/buildkite@1.service → /lib/systemd/system/buildkite@.service.
```

Created 4 of those...

**Comment by ibuclaw** [comment]
Looks like still some quirks to iron out on the runners.
```
./ci.sh: line 72: /usr/bin/time: No such file or directory
```
Hidden amongst a few other failing projects.

**Review by WalterBright — APPROVED** [review]

**Comment by ibuclaw** [comment]
All runs seem to fail anyway (during the `git clean` step?)
```
warning: failed to remove ./: Invalid argument
--
user command error: exit status 1
```

**Review by ibuclaw — CHANGES_REQUESTED** [review]
See errors in CI.

**Comment by ibuclaw** [comment]
Last error is in ldc pipeline by the looks. :-)
```
-- Host D compiler front-end version: 2100
CMake Error at cmake/Modules/FindLLVM.cmake:69 (message):
  No LLVM installation (>= 6.0) found.  Try manually setting the
  'LLVM_ROOT_DIR' or 'LLVM_CONFIG' variables.
Call Stack (most recent call first):
  cmake/Modules/FindLLVM.cmake:80 (_LLVM_FAIL)
  CMakeLists.txt:31 (find_package)
```

**Comment by Geod24** [comment]
Yeah I'm trying a few things. Submitted https://github.com/libmir/mir-core/pull/67 also.

**Comment by Geod24** [comment]
Rebuilding the images and trying one more time...

**Pull request merged**
